export type ActiveTab =
    | 'admin_dashboard' | 'admin_users' | 'admin_lojas' | 'admin_validation' | 'admin_notifications' | 'admin_shop' | 'admin_support'
    | 'admin_api_keys' | 'admin_ai_config' | 'admin_routing' | 'admin_infinitepay' | 'admin_fees' | 'admin_pwa' | 'admin_payouts' | 'admin_cities'
    | 'admin_levels' | 'admin_ratings' | 'admin_security' | 'admin_blacklist' | 'admin_referrals' | 'admin_institutional'
    | 'admin_platform_news' | 'admin_store_finance' | 'admin_wallet_control' | 'admin_claims' | 'admin_maintenance' | 'admin_loan_config' | 'admin_investments'
    | 'admin_slides' | 'admin_city_banners' | 'admin_tips' | 'admin_chat' | 'admin_payment_gateways' | 'admin_mercadopago' | 'admin_pix_config' | 'admin_location_map' | 'admin_base_catalog'
    | 'order_tracking' | 'delivery_navigation'
    | 'admin_store_categories' | 'admin_global_coupons' | 'admin_image_gallery'
    | 'admin_insurance' | 'admin_street_requests' | 'admin_mediation' | 'admin_navigation_config'
    | 'store_drivers_chat'
    | 'profile'
    | 'support'
    | 'shop'
    | 'assistant'
    | 'wallet'
    | 'new_request'
    | 'history'
    | 'store_team'
    | 'store_reports'
    | 'store_performance'
    | 'store_marketing'
    | 'store_integrations'
    | 'store_ratings'
    | 'store_settings'
    | 'store_product_import'
    | 'store_status'
    | 'store_receiving_payment'
    | 'store_finance_panel'
    | 'partner'
    | 'daily_panel'
    | 'driver_marketing'
    | 'route_tools'
    | 'route_list'
    | 'local_history'
    | 'reports'
    | 'tasks'
    | 'zebank'
    | 'about'
    | 'faq'
    | 'solutions'
    | 'benefits'
    | 'notifications'
    | 'cloud'
    | 'settings'
    | 'associate_driver'
    | 'associate_orders'
    | 'status'
    | 'heatmap'
    | 'addresses'
    | 'privacy'
    | 'zepay_store'
    | 'upgrade_to_partner'
    | 'install_app'
    | 'internal_orders'
    | 'internal_orders_new'
    | 'store_catalog'
    | 'store_print_catalog'
    | 'store_api_docs'
    | 'store_promotions'
    | 'store_highlight'
    | 'streets_list'
    | 'score'
    | 'store_loans'
    | 'loans'
    | 'collaborator_area'
    | 'internal_chat'
    | 'chat'
    | 'forgot_password'
    | 'login'
    | 'signup'
    | 'partner_store'
    | 'partner_delivery'
    | 'insurance'
    | 'home'
    | 'my_orders'
    | 'digital_menu'
    | 'store_public_chat'
    | 'street_request'
    | 'zepoint'
    | 'not_found';
